// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RunningTracker.API.Data;

#nullable disable

namespace RunningTracker.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("RunningTracker.API.Models.PhaseInfo", b =>
                {
                    b.Property<int>("Phase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DotColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Phase");

                    b.ToTable("PhaseInfos");

                    b.HasData(
                        new
                        {
                            Phase = 1,
                            DotColor = "#10b981",
                            Label = "Phase 1 · Build the Habit"
                        },
                        new
                        {
                            Phase = 2,
                            DotColor = "#38bdf8",
                            Label = "Phase 2 · Build Endurance"
                        },
                        new
                        {
                            Phase = 3,
                            DotColor = "#f59e0b",
                            Label = "Phase 3 · Push to 10K"
                        });
                });

            modelBuilder.Entity("RunningTracker.API.Models.ScheduleDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScheduleDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = "Mon",
                            Icon = "🏋️",
                            IsRun = false,
                            Label = "Strength",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Day = "Tue",
                            Icon = "🚴",
                            IsRun = false,
                            Label = "Bike",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Day = "Wed",
                            Icon = "🏃",
                            IsRun = true,
                            Label = "Run 1",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Day = "Thu",
                            Icon = "🏋️",
                            IsRun = false,
                            Label = "Strength / Rest",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Day = "Fri",
                            Icon = "🚴",
                            IsRun = false,
                            Label = "Bike",
                            Order = 5
                        },
                        new
                        {
                            Id = 6,
                            Day = "Sat",
                            Icon = "🏃",
                            IsRun = true,
                            Label = "Run 2",
                            Order = 6
                        },
                        new
                        {
                            Id = 7,
                            Day = "Sun",
                            Icon = "😴",
                            IsRun = false,
                            Label = "Rest",
                            Order = 7
                        });
                });

            modelBuilder.Entity("RunningTracker.API.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Week", "SessionNumber")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("RunningTracker.API.Models.TrainingWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Session1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Session2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Week")
                        .IsUnique();

                    b.ToTable("TrainingWeeks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = "30 min each",
                            Note = "Keep it easy — conversational pace!",
                            Phase = 1,
                            Session1 = "1 min run / 2 min walk × 8",
                            Session2 = "1 min run / 2 min walk × 8",
                            Week = 1
                        },
                        new
                        {
                            Id = 2,
                            Duration = "30 min each",
                            Note = "Focus on breathing rhythm.",
                            Phase = 1,
                            Session1 = "1.5 min run / 1.5 min walk × 10",
                            Session2 = "1.5 min run / 1.5 min walk × 10",
                            Week = 2
                        },
                        new
                        {
                            Id = 3,
                            Duration = "30 min each",
                            Note = "You're running more than walking now!",
                            Phase = 1,
                            Session1 = "2 min run / 1 min walk × 10",
                            Session2 = "2 min run / 1 min walk × 10",
                            Week = 3
                        },
                        new
                        {
                            Id = 4,
                            Duration = "~28 min each",
                            Note = "End of Phase 1 — great work!",
                            Phase = 1,
                            Session1 = "3 min run / 1 min walk × 7",
                            Session2 = "3 min run / 1 min walk × 7",
                            Week = 4
                        },
                        new
                        {
                            Id = 5,
                            Duration = "30 min each",
                            Note = "Longer blocks — trust the process.",
                            Phase = 2,
                            Session1 = "5 min run / 1 min walk × 5",
                            Session2 = "5 min run / 1 min walk × 5",
                            Week = 5
                        },
                        new
                        {
                            Id = 6,
                            Duration = "~27 min each",
                            Note = "Speed is still irrelevant — just move!",
                            Phase = 2,
                            Session1 = "8 min run / 1 min walk × 3",
                            Session2 = "8 min run / 1 min walk × 3",
                            Week = 6
                        },
                        new
                        {
                            Id = 7,
                            Duration = "33 min each",
                            Note = "Almost continuous running.",
                            Phase = 2,
                            Session1 = "10 min run / 1 min walk × 3",
                            Session2 = "10 min run / 1 min walk × 3",
                            Week = 7
                        },
                        new
                        {
                            Id = 8,
                            Duration = "32 min each",
                            Note = "Halfway through the plan!",
                            Phase = 2,
                            Session1 = "15 min run / 1 min walk × 2",
                            Session2 = "15 min run / 1 min walk × 2",
                            Week = 8
                        },
                        new
                        {
                            Id = 9,
                            Duration = "20 min each",
                            Note = "First continuous run — milestone!",
                            Phase = 2,
                            Session1 = "20 min continuous run",
                            Session2 = "20 min continuous run",
                            Week = 9
                        },
                        new
                        {
                            Id = 10,
                            Duration = "25 min each",
                            Note = "That's roughly a 5K. You're a runner!",
                            Phase = 2,
                            Session1 = "25 min continuous run",
                            Session2 = "25 min continuous run",
                            Week = 10
                        },
                        new
                        {
                            Id = 11,
                            Duration = "53 min total",
                            Note = "Phase 3 — building toward 10K.",
                            Phase = 3,
                            Session1 = "28 min easy",
                            Session2 = "25 min easy",
                            Week = 11
                        },
                        new
                        {
                            Id = 12,
                            Duration = "58 min total",
                            Note = "+10% weekly rule — steady progress.",
                            Phase = 3,
                            Session1 = "30 min easy",
                            Session2 = "28 min easy",
                            Week = 12
                        },
                        new
                        {
                            Id = 13,
                            Duration = "65 min total",
                            Note = "Legs getting stronger every week.",
                            Phase = 3,
                            Session1 = "35 min easy",
                            Session2 = "30 min easy",
                            Week = 13
                        },
                        new
                        {
                            Id = 14,
                            Duration = "70 min total",
                            Note = "You can start picking up pace slightly.",
                            Phase = 3,
                            Session1 = "40 min easy",
                            Session2 = "30 min easy",
                            Week = 14
                        },
                        new
                        {
                            Id = 15,
                            Duration = "80 min total",
                            Note = "Almost there — one more week!",
                            Phase = 3,
                            Session1 = "45 min easy",
                            Session2 = "35 min easy",
                            Week = 15
                        },
                        new
                        {
                            Id = 16,
                            Duration = "~90 min total",
                            Note = "That long run IS your 10K. You did it!",
                            Phase = 3,
                            Session1 = "55-60 min easy",
                            Session2 = "30 min easy",
                            Week = 16
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
